// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFirst.Models;

[Keyless]
public partial class AuthorsBook
{
    [StringLength(100)]
    [Unicode(false)]
    public string AuthorName { get; set; } = null!;

    public int? CountOfBooks { get; set; }
}