// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFirst.Models;

[PrimaryKey("BookIsbn", "AuthorId")]
[Table("Books_Authors", Schema = "Library")]
public partial class BooksAuthor
{
    [Key]
    [Column("BookISBN")]
    [StringLength(20)]
    [Unicode(false)]
    public string BookIsbn { get; set; } = null!;

    [Key]
    public int AuthorId { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("BooksAuthors")]
    public virtual Author Author { get; set; } = null!;

    [ForeignKey("BookIsbn")]
    [InverseProperty("BooksAuthors")]
    public virtual Book BookIsbnNavigation { get; set; } = null!;
}