// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFirst.Models;

[Table("BookCopies", Schema = "Library")]
public partial class BookCopy
{
    [Key]
    public int CopyId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? Condition { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? CurrentStatus { get; set; }

    public int? BranchId { get; set; }

    [Column("BookISBN")]
    [StringLength(20)]
    [Unicode(false)]
    public string? BookIsbn { get; set; }

    [ForeignKey("BookIsbn")]
    [InverseProperty("BookCopies")]
    public virtual Book? BookIsbnNavigation { get; set; }

    [InverseProperty("BookCopy")]
    public virtual ICollection<BorrowTransaction> BorrowTransactions { get; set; } = new List<BorrowTransaction>();

    [ForeignKey("BranchId")]
    [InverseProperty("BookCopies")]
    public virtual Branch? Branch { get; set; }
}