// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFirst.Models;

[Table("BorrowTransactions", Schema = "Library")]
public partial class BorrowTransaction
{
    [Key]
    public int TransactionId { get; set; }

    public DateOnly BorrowDate { get; set; }

    public int BookCopyId { get; set; }

    public int MemberId { get; set; }

    public DateOnly? ReturnDate { get; set; }

    public DateOnly? DueDate { get; set; }

    [ForeignKey("BookCopyId")]
    [InverseProperty("BorrowTransactions")]
    public virtual BookCopy BookCopy { get; set; } = null!;

    [InverseProperty("BorrowTran")]
    public virtual Fine? Fine { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("BorrowTransactions")]
    public virtual Member Member { get; set; } = null!;
}