// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DatabaseFirst.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DatabaseFirst.Models
{
    public partial class CityLibraryDbContext
    {
        private ICityLibraryDbContextProcedures? _procedures;

        public virtual ICityLibraryDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CityLibraryDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICityLibraryDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class CityLibraryDbContextProcedures : ICityLibraryDbContextProcedures
    {
        private readonly CityLibraryDbContext _context;

        public CityLibraryDbContextProcedures(CityLibraryDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_AuthorBooksResult>?> SP_AuthorBooksAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_AuthorBooksResult>("EXEC @returnValue = [dbo].[SP_AuthorBooks]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
