// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFirst.Models;

[Table("Fines", Schema = "Library")]
[Index("BorrowTranId", Name = "UQ_BorrowTranId", IsUnique = true)]
[Index("BorrowTranId", Name = "UQ__Fines__960D8335058FFAD4", IsUnique = true)]
public partial class Fine
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Amount { get; set; }

    public DateOnly? IssueDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? PaymentStatus { get; set; }

    public int? BorrowTranId { get; set; }

    [ForeignKey("BorrowTranId")]
    [InverseProperty("Fine")]
    public virtual BorrowTransaction? BorrowTran { get; set; }
}