// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DatabaseFirst.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DatabaseFirst.Models
{
    public partial interface ICityLibraryDbContextProcedures
    {
        Task<List<SP_AuthorBooksResult>?> SP_AuthorBooksAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
