// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DatabaseFirst.Models
{
    public partial class SP_AuthorBooksResult
    {
        [StringLength(100)]
        public string FullName { get; set; } = default!;
        public int? CountOfBooks { get; set; }
    }
}
