// <auto-generated />
using System;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseFirst.Migrations
{
    [DbContext(typeof(CityLibraryDbContext))]
    partial class CityLibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseFirst.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Authors__3214EC0785D88615");

                    b.ToTable("Authors", "Library");
                });

            modelBuilder.Entity("DatabaseFirst.Models.AuthorsBook", b =>
                {
                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CountOfBooks")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("AuthorsBooks", (string)null);
                });

            modelBuilder.Entity("DatabaseFirst.Models.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<string>("BookCategory")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Edition")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Isbn")
                        .HasName("PK__Books__447D36EB11731A7D");

                    b.ToTable("Books", "Library");
                });

            modelBuilder.Entity("DatabaseFirst.Models.BookCopy", b =>
                {
                    b.Property<int>("CopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CopyId"));

                    b.Property<string>("BookIsbn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("BookISBN");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CurrentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Available")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CurrentStatus");

                    b.HasKey("CopyId")
                        .HasName("PK__BookCopi__C26CCCC544609DF6");

                    b.HasIndex("BookIsbn");

                    b.HasIndex("BranchId");

                    b.ToTable("BookCopies", "Library");
                });

            modelBuilder.Entity("DatabaseFirst.Models.BooksAuthor", b =>
                {
                    b.Property<string>("BookIsbn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("BookISBN");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookIsbn", "AuthorId")
                        .HasName("PK__Books_Au__69D776C8A41B1C2A");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books_Authors", "Library");
                });

            modelBuilder.Entity("DatabaseFirst.Models.BorrowTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BorrowDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.HasKey("TransactionId")
                        .HasName("PK__BorrowTr__55433A6B67301419");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("MemberId");

                    b.ToTable("BorrowTransactions", "Library");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Branches__3214EC0736C7D3BF");

                    b.HasIndex(new[] { "ManagerId" }, "UQ__Branches__3BA2AAE0E9F02DE1")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("Branches", "Management");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("BorrowTranId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Fines__3214EC07AC04D47B");

                    b.HasIndex(new[] { "BorrowTranId" }, "UQ_BorrowTranId")
                        .IsUnique()
                        .HasFilter("[BorrowTranId] IS NOT NULL");

                    b.HasIndex(new[] { "BorrowTranId" }, "UQ__Fines__960D8335058FFAD4")
                        .IsUnique()
                        .HasFilter("[BorrowTranId] IS NOT NULL");

                    b.ToTable("Fines", "Library");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Librarian", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Libraria__3214EC0737786BE0");

                    b.ToTable("Librarians", "Management");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Member", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipId"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("MembershipDate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MembershipId")
                        .HasName("PK__Members__92A786791E71E3FE");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("DatabaseFirst.Models.BookCopy", b =>
                {
                    b.HasOne("DatabaseFirst.Models.Book", "BookIsbnNavigation")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookIsbn")
                        .HasConstraintName("FK_Copy_Book");

                    b.HasOne("DatabaseFirst.Models.Branch", "Branch")
                        .WithMany("BookCopies")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_Copy_Branch");

                    b.Navigation("BookIsbnNavigation");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DatabaseFirst.Models.BooksAuthor", b =>
                {
                    b.HasOne("DatabaseFirst.Models.Author", "Author")
                        .WithMany("BooksAuthors")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_BA_Author");

                    b.HasOne("DatabaseFirst.Models.Book", "BookIsbnNavigation")
                        .WithMany("BooksAuthors")
                        .HasForeignKey("BookIsbn")
                        .IsRequired()
                        .HasConstraintName("FK_BA_Book");

                    b.Navigation("Author");

                    b.Navigation("BookIsbnNavigation");
                });

            modelBuilder.Entity("DatabaseFirst.Models.BorrowTransaction", b =>
                {
                    b.HasOne("DatabaseFirst.Models.BookCopy", "BookCopy")
                        .WithMany("BorrowTransactions")
                        .HasForeignKey("BookCopyId")
                        .IsRequired()
                        .HasConstraintName("FK_BT_Copy");

                    b.HasOne("DatabaseFirst.Models.Member", "Member")
                        .WithMany("BorrowTransactions")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_BT_Member");

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Branch", b =>
                {
                    b.HasOne("DatabaseFirst.Models.Librarian", "Manager")
                        .WithOne("Branch")
                        .HasForeignKey("DatabaseFirst.Models.Branch", "ManagerId")
                        .HasConstraintName("FK__Branches__Manage__3A81B327");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Fine", b =>
                {
                    b.HasOne("DatabaseFirst.Models.BorrowTransaction", "BorrowTran")
                        .WithOne("Fine")
                        .HasForeignKey("DatabaseFirst.Models.Fine", "BorrowTranId")
                        .HasConstraintName("FK_FineTran");

                    b.Navigation("BorrowTran");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Author", b =>
                {
                    b.Navigation("BooksAuthors");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Book", b =>
                {
                    b.Navigation("BookCopies");

                    b.Navigation("BooksAuthors");
                });

            modelBuilder.Entity("DatabaseFirst.Models.BookCopy", b =>
                {
                    b.Navigation("BorrowTransactions");
                });

            modelBuilder.Entity("DatabaseFirst.Models.BorrowTransaction", b =>
                {
                    b.Navigation("Fine");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Branch", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Librarian", b =>
                {
                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DatabaseFirst.Models.Member", b =>
                {
                    b.Navigation("BorrowTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
