// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test.Models;

[Table("Books", Schema = "Library")]
public partial class Book
{
    [Key]
    [Column("ISBN")]
    [StringLength(20)]
    [Unicode(false)]
    public string Isbn { get; set; } = null!;

    public int? PublicationYear { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Title { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string? Edition { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? BookCategory { get; set; }

    [InverseProperty("BookIsbnNavigation")]
    public virtual ICollection<BookCopy> BookCopies { get; set; } = new List<BookCopy>();

    [InverseProperty("BookIsbnNavigation")]
    public virtual ICollection<BooksAuthor> BooksAuthors { get; set; } = new List<BooksAuthor>();
}