// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test.Models;

[Table("Branches", Schema = "Management")]
[Index("ManagerId", Name = "UQ__Branches__3BA2AAE0E9F02DE1", IsUnique = true)]
public partial class Branch
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    [StringLength(200)]
    [Unicode(false)]
    public string? Address { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? PhoneNumber { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string? OpeningHours { get; set; }

    public int? ManagerId { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<BookCopy> BookCopies { get; set; } = new List<BookCopy>();

    [ForeignKey("ManagerId")]
    [InverseProperty("Branch")]
    public virtual Librarian? Manager { get; set; }
}