// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Test.Models;

public partial class CityLibraryDbContext : DbContext
{
    public CityLibraryDbContext()
    {
    }

    public CityLibraryDbContext(DbContextOptions<CityLibraryDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Author> Authors { get; set; }

    public virtual DbSet<AuthorsBook> AuthorsBooks { get; set; }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<BookCopy> BookCopies { get; set; }

    public virtual DbSet<BooksAuthor> BooksAuthors { get; set; }

    public virtual DbSet<BorrowTransaction> BorrowTransactions { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<Fine> Fines { get; set; }

    public virtual DbSet<Librarian> Librarians { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	
        => optionsBuilder.UseSqlServer(
	"Data Source=.;Initial Catalog=CityLibraryDb;Integrated Security=True;TrustServerCertificate=True"
);


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Author>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Authors__3214EC0785D88615");
        });

        modelBuilder.Entity<AuthorsBook>(entity =>
        {
            entity.ToView("AuthorsBooks");
        });

        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.Isbn).HasName("PK__Books__447D36EB11731A7D");
        });

        modelBuilder.Entity<BookCopy>(entity =>
        {
            entity.HasKey(e => e.CopyId).HasName("PK__BookCopi__C26CCCC544609DF6");

            entity.Property(e => e.CurrentStatus)
                .HasDefaultValue("Available")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CurrentStatus");

            entity.HasOne(d => d.BookIsbnNavigation).WithMany(p => p.BookCopies).HasConstraintName("FK_Copy_Book");

            entity.HasOne(d => d.Branch).WithMany(p => p.BookCopies).HasConstraintName("FK_Copy_Branch");
        });

        modelBuilder.Entity<BooksAuthor>(entity =>
        {
            entity.HasKey(e => new { e.BookIsbn, e.AuthorId }).HasName("PK__Books_Au__69D776C8A41B1C2A");

            entity.HasOne(d => d.Author).WithMany(p => p.BooksAuthors)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BA_Author");

            entity.HasOne(d => d.BookIsbnNavigation).WithMany(p => p.BooksAuthors)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BA_Book");
        });

        modelBuilder.Entity<BorrowTransaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__BorrowTr__55433A6B67301419");

            entity.HasOne(d => d.BookCopy).WithMany(p => p.BorrowTransactions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BT_Copy");

            entity.HasOne(d => d.Member).WithMany(p => p.BorrowTransactions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BT_Member");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Branches__3214EC0736C7D3BF");

            entity.HasOne(d => d.Manager).WithOne(p => p.Branch).HasConstraintName("FK__Branches__Manage__3A81B327");
        });

        modelBuilder.Entity<Fine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Fines__3214EC07AC04D47B");

            entity.HasOne(d => d.BorrowTran).WithOne(p => p.Fine).HasConstraintName("FK_FineTran");
        });

        modelBuilder.Entity<Librarian>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Libraria__3214EC0737786BE0");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.MembershipId).HasName("PK__Members__92A786791E71E3FE");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}